// import shuttleImg from '../assets/spaceshuttle.png';

const HeroSection = () => {
  return (

    <div className="hero-container">

      <h1 className="hero-title">History, But With a Twist</h1>

      <p className="hero-subtext">
        Explore alternate history scenarios generated by AI<br />
        Choose a style and see how the past could have unfolded differently

      </p>

      <div className="example-bubbles">

        <span className="example-bubble">What if the British Empire returned?</span>
        <span className="example-bubble">What if Germany won WWI?</span>
        <span className="example-bubble">What if Julius Caesar never existed?</span>

      </div>

      <button className="launch-button">Launch Space Shuttle</button>

      <div className="shuttle-placeholder">
       
       {/* <img src={shuttleImg} alt="Space Shuttle"></img> */}

      </div>

    </div>
  );
};

export default HeroSection;
